modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="tactical_cards" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Tactical Graphic cards" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="assets/tactical_cards.png" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Hope ur guys know what happened with GTX 690.
This Mod adde NVIDIA GTX 690 into Minecraft as a Weapon.
'''