modLoader="javafml"
loaderVersion="[40,)"
license="GPL v3"
issueTrackerURL="https://github.com/Arrokoth486958/Tactical-Graphic-cards" #optional
[[mods]]
modId="tactical_cards"
version="1.0a-build-2022527"
displayName="Tactical Graphic cards"
logoFile="icon.png"
authors="Arrokoth, Radekemia"
description='''
Hope ur guys know what happened with GTX 690.
This mod added NVIDIA GTX 690 and other cards into Minecraft as weapons.
'''